## question 1. Create a null vector of size 10 but fifth value which is 1

In [7]:
import numpy as np

In [8]:
vector = np.zeros(10, dtype = int)
vector[4]=1
print(vector)

[0 0 0 0 1 0 0 0 0 0]


## question 2. Create a vector with values ranging from 10 to 49.

In [10]:
np.arange(start = 10, stop = 50, step = 1, dtype = int)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## question 3: create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
m = np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## question 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [17]:
z = np.nonzero([1,2,0,0,4,0])
print('the indices are', z)

the indices are (array([0, 1, 4], dtype=int64),)


## question 5: create a 10x10 matrix and find max, min values

In [12]:
matrix = np.random.random((10,10))
print(matrix)

matmin, matmax = matrix.min(), matrix.max()
print('minimum and maximum values are', matmin, matmax)

[[0.39899737 0.07801399 0.27130427 0.62854572 0.92448311 0.85087581
  0.98793    0.43449384 0.9518951  0.64193282]
 [0.02220651 0.1925813  0.1701701  0.86438321 0.17959791 0.42645965
  0.6272522  0.97235523 0.92439373 0.51128058]
 [0.499999   0.55430356 0.06785354 0.0649778  0.23835294 0.41286776
  0.67216013 0.84530137 0.09318133 0.63525867]
 [0.81634304 0.14920527 0.76361959 0.68185731 0.7847741  0.14917641
  0.38806551 0.80303473 0.54595269 0.03634805]
 [0.79456499 0.38691303 0.1732731  0.88515849 0.67840727 0.89042992
  0.05725843 0.12131955 0.76174967 0.79958353]
 [0.9654434  0.43027747 0.21195584 0.30026831 0.39021805 0.08126408
  0.1824782  0.94819425 0.01776364 0.15517104]
 [0.42850091 0.68031796 0.84455008 0.04736212 0.67673947 0.55439431
  0.98303813 0.12590665 0.97578049 0.48094441]
 [0.49628467 0.01722012 0.79603116 0.95968765 0.13266726 0.65039323
  0.95747972 0.29325946 0.81546434 0.76836932]
 [0.82937404 0.90121771 0.93096294 0.54613103 0.89068319 0.83963941
  0.01066621

In [13]:
matrix.shape

(10, 10)

## question 6: create a random vector size 30 and find mean value

In [18]:
v = np.random.random(30)
print('random vector is: ', v)
print()
print('mean is:', np.mean(v))

random vector is:  [0.68722587 0.46087614 0.48615664 0.78937574 0.34277638 0.43839286
 0.44362152 0.21150386 0.23508917 0.23959756 0.67348287 0.90862762
 0.99079593 0.9298288  0.54484764 0.61038457 0.26728887 0.8863892
 0.90514991 0.10170369 0.57958717 0.12980527 0.66401585 0.07727587
 0.71501743 0.6367333  0.7219305  0.72949518 0.75734786 0.20343208]

mean is: 0.545591844744784
